default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: basic_login_app_dev

test:
  <<: *default
  database: basic_login_app_test

production:
  <<: *default
  database: basic_login_app_production
